---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/lcarva/infra-deployments-1.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-main
