apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spi-system
namePrefix: spi-

resources:
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/vault/openshift?ref=50959cd7ead4baa44f6c44fdcf6bea395718427a
  - vault_role.yaml
  - vault_rolebinding.yaml

patches:
- target:
    kind: Route
    name: vault
  patch: |-
    - op: replace
      path: /spec/to/name
      value: spi-vault
- target:
    kind: StatefulSet
    name: vault
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: docker.io/hashicorp/vault:1.10.3

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: spi-vault
    $patch: delete
