---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/lcarva/pipeline-service/operator/gitops/argocd/grafana/?ref=9850f32012a8ca21501cbb06d38a91a6a747f1b1
